// <auto-generated />
using System;
using Abc.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Abc.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260531201844_v.31.05.26alreadyExistsErrorRepair")]
    partial class v310526alreadyExistsErrorRepair
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Abc.Data.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Abc.Data.Creator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Creators");
                });

            modelBuilder.Entity("Abc.Data.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SeatCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("durationMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SeatCategoryId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Abc.Data.EventCreator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("EventId");

                    b.ToTable("EventCreators");
                });

            modelBuilder.Entity("Abc.Data.EventGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GenreId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("GenreId");

                    b.ToTable("EventGenres");
                });

            modelBuilder.Entity("Abc.Data.EventObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("HallId");

                    b.ToTable("EventObjects");
                });

            modelBuilder.Entity("Abc.Data.EventSeatCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SeatCategoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("SeatCategoryId");

                    b.ToTable("EventSeatCategories");
                });

            modelBuilder.Entity("Abc.Data.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("content")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Abc.Data.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Abc.Data.Hall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HallCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("NrOfRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NrOfSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HallCategoryId");

                    b.ToTable("Halls");
                });

            modelBuilder.Entity("Abc.Data.HallCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HallCategories");
                });

            modelBuilder.Entity("Abc.Data.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Abc.Data.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Abc.Data.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Abc.Data.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HallId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SeatCategoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("SeatCategoryId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Abc.Data.SeatCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SeatCategories");
                });

            modelBuilder.Entity("Abc.Data.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EventObjectId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SeatId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("EventObjectId");

                    b.HasIndex("PersonId");

                    b.HasIndex("SeatId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Abc.Data.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("PersonId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Abc.Data.Cart", b =>
                {
                    b.HasOne("Abc.Data.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Abc.Data.Event", b =>
                {
                    b.HasOne("Abc.Data.Creator", null)
                        .WithMany("Events")
                        .HasForeignKey("CreatorId");

                    b.HasOne("Abc.Data.SeatCategory", null)
                        .WithMany("Events")
                        .HasForeignKey("SeatCategoryId");
                });

            modelBuilder.Entity("Abc.Data.EventCreator", b =>
                {
                    b.HasOne("Abc.Data.Creator", "Creator")
                        .WithMany("EventCreators")
                        .HasForeignKey("CreatorId");

                    b.HasOne("Abc.Data.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.Navigation("Creator");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Abc.Data.EventGenre", b =>
                {
                    b.HasOne("Abc.Data.Event", "Event")
                        .WithMany("EventGenres")
                        .HasForeignKey("EventId");

                    b.HasOne("Abc.Data.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.Navigation("Event");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Abc.Data.EventObject", b =>
                {
                    b.HasOne("Abc.Data.Event", "Event")
                        .WithMany("EventObjects")
                        .HasForeignKey("EventId");

                    b.HasOne("Abc.Data.Hall", "Hall")
                        .WithMany("EventObjects")
                        .HasForeignKey("HallId");

                    b.Navigation("Event");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("Abc.Data.EventSeatCategory", b =>
                {
                    b.HasOne("Abc.Data.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("Abc.Data.SeatCategory", "SeatCategory")
                        .WithMany("EventSeatCategories")
                        .HasForeignKey("SeatCategoryId");

                    b.Navigation("Event");

                    b.Navigation("SeatCategory");
                });

            modelBuilder.Entity("Abc.Data.Feedback", b =>
                {
                    b.HasOne("Abc.Data.Event", "Event")
                        .WithMany("Feedbacks")
                        .HasForeignKey("EventId");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Abc.Data.Genre", b =>
                {
                    b.HasOne("Abc.Data.Event", null)
                        .WithMany("Genres")
                        .HasForeignKey("EventId");
                });

            modelBuilder.Entity("Abc.Data.Hall", b =>
                {
                    b.HasOne("Abc.Data.HallCategory", "HallCategory")
                        .WithMany("Halls")
                        .HasForeignKey("HallCategoryId");

                    b.Navigation("HallCategory");
                });

            modelBuilder.Entity("Abc.Data.Payment", b =>
                {
                    b.HasOne("Abc.Data.Cart", "Cart")
                        .WithMany("Payments")
                        .HasForeignKey("CartId");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Abc.Data.Person", b =>
                {
                    b.HasOne("Abc.Data.Role", null)
                        .WithMany("People")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("Abc.Data.Seat", b =>
                {
                    b.HasOne("Abc.Data.Hall", "Hall")
                        .WithMany("Seats")
                        .HasForeignKey("HallId");

                    b.HasOne("Abc.Data.SeatCategory", "SeatCategory")
                        .WithMany()
                        .HasForeignKey("SeatCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Hall");

                    b.Navigation("SeatCategory");
                });

            modelBuilder.Entity("Abc.Data.Ticket", b =>
                {
                    b.HasOne("Abc.Data.Cart", "Cart")
                        .WithMany("Tickets")
                        .HasForeignKey("CartId");

                    b.HasOne("Abc.Data.EventObject", "EventObject")
                        .WithMany("Tickets")
                        .HasForeignKey("EventObjectId");

                    b.HasOne("Abc.Data.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("Abc.Data.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId");

                    b.Navigation("Cart");

                    b.Navigation("EventObject");

                    b.Navigation("Person");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Abc.Data.UserRole", b =>
                {
                    b.HasOne("Abc.Data.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("Abc.Data.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Abc.Data.Cart", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Abc.Data.Creator", b =>
                {
                    b.Navigation("EventCreators");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("Abc.Data.Event", b =>
                {
                    b.Navigation("EventGenres");

                    b.Navigation("EventObjects");

                    b.Navigation("Feedbacks");

                    b.Navigation("Genres");
                });

            modelBuilder.Entity("Abc.Data.EventObject", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Abc.Data.Hall", b =>
                {
                    b.Navigation("EventObjects");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Abc.Data.HallCategory", b =>
                {
                    b.Navigation("Halls");
                });

            modelBuilder.Entity("Abc.Data.Role", b =>
                {
                    b.Navigation("People");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Abc.Data.SeatCategory", b =>
                {
                    b.Navigation("EventSeatCategories");

                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
